words = [
    "CLI",
    "Caddy's",
    "Caddyfile",
    "Docker's",
    "Emi",
    "JST",
    "Mockall",
    "Reiwa",
    "SNS",
    "Swatinem",
    "TLS",
    "Twemoji",
    "Utc",
    "adduser",
    "buildx",
    "caddy",
    "clippy",
    "cov",
    "crypto",
    "direnv",
    "dotenv",
    "dtolnay",
    "envrc",
    "f'docker",
    "gha",
    "healthcheck",
    "isready",
    "justfile",
    "mkdir",
    "nicknovitski",
    "nixbuild",
    "nixos",
    "nixpkgs",
    "noahkawaguchi",
    "oxalica",
    "pkgs",
    "pwa",
    "requester's",
    "requesters",
    "rustfmt",
    "rustup",
    "sqlx",
    "sslmode",
    "svc",
    "tokio",
    "uow",
    "utoipa",
    "wget",
    "xzf",
]
ignore_paths = [
    "Cargo.lock",
    "flake.lock",
    ".sqlx/**/*",
]
ignore_patterns = ['\b[a-fA-F0-9]{64}\b']
