comment_width = 100
fn_single_line = true
group_imports = "One"
imports_granularity = "Crate"
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
struct_lit_width = 100
where_single_line = true
wrap_comments = true
